version: "3.8"

services:

  gitea:
    image: docker.io/gitea/gitea:1.23.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - jenkins
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:3000"
      - "222:22"

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-agent-dind
    container_name: jenkins-agent-dind
    restart: unless-stopped
    privileged: true
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./java:/var/jenkins_home/java
      - ./docker_data/lib/docker:/var/lib/docker
      - ./repository:/var/jenkins_home/.m2/repository
    depends_on:
      - jenkins
    init: true
    command: >
      -url http://jenkins-app:8080/
      -secret 2d05730633ffed3f80cb72e1b2a9f752e04fb6f9af25c3e90b046ef91291ee54
      -name agent1
      -webSocket
      -workDir /home/jenkins

  # Jenkins Server
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-app
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agent
    volumes:
      - jenkins-data:/var/jenkins_home
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data
  agent-ssh:
    image: jenkins/ssh-agent:alpine-jdk17
    container_name: agent-ssh
    ports:
      - "2222:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6KY/9QjcwSlZbtFKp3idVoxgNnlvgX7eO9mXnK/5yfdA9zSOBdrYUlYdnXb6gJ3d7ogbH21Wu70PXNdu8G905Ogi2hwtLxkD45ZFLE1V95LG1ZrK3I2KmuTHdaKhpISKdBNcsSS52NWVLE/atiMVmNcRA6jP567LmzBTUJEaJmOokrrJIDtKTsKBJ6qVd4v+uJprGWesyFZAdUF2shqB10zMcPk2SkTNXDBTcBLas6+9Ld7Ypp1cQk4rrIOTiKt9/EdQ61FALXjKEOcGep+AoPaF78zPBl1pUrzlQNfpFzQsIQNXqiXPdHudS0lJrFE9Kr722iF1/qQ7FWfgifb5zCItWmO7NUnLQlrOzwiZYECV5fbfy3PpB10nA0yd3VXv+mP2FekJL/umzFzjD5uP51FPRBAOC7HRZdBLNega/JuPFdRVj0oZ+Z0p5eR3V6NxM39iod27DNqEdUfbyMrcuY/FkU20+UKXv2BldOEQ+qgRCET8tTEzvM1rYv8VxxL8= nik@n
    restart: unless-stopped
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-data: