version: "3.8"

services:

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-agent-dind
    container_name: jenkins-agent-dind
    restart: unless-stopped
    privileged: true
    networks:
      - jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./java:/var/jenkins_home/java
      - ./docker_data/lib/docker:/var/lib/docker
      - ./repository:/var/jenkins_home/.m2/repository
    depends_on:
      - jenkins
    init: true
    command: >
      -url http://jenkins-app:8080/
      -secret 98e6d28bbb50bcbef2f4e73150023a8b0c8d71eacc902de24885c7a1902192bb
      -name agent1
      -webSocket
      -workDir /home/jenkins

  # Jenkins Server
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-app
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8070:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agent
    volumes:
      - ./jenkins-data:/var/jenkins_home

networks:
  jenkins:

volumes:
  jenkins-data:
